WIP: this doesn't work, the dependencies are executed first, and then the page is ready before planner app.js can execute. This means we get because angular.module('app') didn't execute yet.
Uncaught Error: [$injector:modulerr] Failed to instantiate module app due to:
Error: [$injector:nomod] Module 'app' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument.

https://errors.angularjs.org/1.8.2/$injector/modulerr?p0=app&p1=Error%3A%20%5B%24injector%3Anomod%5D%20Module%20'app'%20is%20not%20available!%20You%20either%20misspelled%20the%20module%20name%20or%20forgot%20to%20load%20it.%20If%20registering%20a%20module%20ensure%20that%20you%20specify%20the%20dependencies%20as%20the%20second%20argument.%0Ahttps%3A%2F%2Ferrors.angularjs.org%2F1.8.2%2F%24injector%2Fnomod%3Fp0%3Dapp%0A%20%20%20%20at%20http%3A%2F%2Flocalhost%3A8080%2Fshared-angular.bundle.js%3A13199%3A12%0A%20%20%20%20at%20http%3A%2F%2Flocalhost%3A8080%2Fshared-angular.bundle.js%3A15392%3A17%0A%20%20%20%20at%20ensure%20(http%3A%2F%2Flocalhost%3A8080%2Fshared-angular.bundle.js%3A15313%3A38)%0A%20%20%20%20at%20module%20(http%3A%2F%2Flocalhost%3A8080%2Fshared-angular.bundle.js%3A15390%3A14)%0A%20%20%20%20at%20http%3A%2F%2Flocalhost%3A8080%2Fshared-angular.bundle.js%3A18164%3A22%0A%20%20%20%20at%20forEach%20(http%3A%2F%2Flocalhost%3A8080%2Fshared-angular.bundle.js%3A13449%3A20)%0A%20%20%20%20at%20loadModules%20(http%3A%2F%2Flocalhost%3A8080%2Fshared-angular.bundle.js%3A18148%3A5)%0A%20%20%20%20at%20createInjector%20(http%3A%2F%2Flocalhost%3A8080%2Fshared-angular.bundle.js%3A18065%3A19)%0A%20%20%20%20at%20doBootstrap%20(http%3A%2F%2Flocalhost%3A8080%2Fshared-angular.bundle.js%3A15024%3A20)%0A%20%20%20%20at%20bootstrap%20(http%3A%2F%2Flocalhost%3A8080%2Fshared-angular.bundle.js%3A15045%3A12)
    at angular.js:138
    at angular.js:5127
    at forEach (angular.js:388)
    at loadModules (angular.js:5087)
    at createInjector (angular.js:5004)
    at doBootstrap (angular.js:1963)
    at bootstrap (angular.js:1984)
    at angularInit (angular.js:1869)
    at angular.js:36595
    at HTMLDocument.trigger (angular.js:3587)
(anonymous) @ angular.js:138
(anonymous) @ angular.js:5127
forEach @ angular.js:388
loadModules @ angular.js:5087
createInjector @ angular.js:5004
doBootstrap @ angular.js:1963
bootstrap @ angular.js:1984
angularInit @ angular.js:1869
(anonymous) @ angular.js:36595
trigger @ angular.js:3587