Fix strange failure with even stranger hack.
  1 Planner display

    1.1 Plan
      × should be removable (5 secs)
        - Expected [] to be array of size 1.

        P:/projects/workspace/net.twisterrob.cinema/Heroku/test/src/plans.spec.js:18:29
                                cinemaPlan.listPlans();
                                expect(cinemaPlan.list).toBeDisplayed();
                                expect(cinemaPlan.items).toBeArrayOfSize(1);
                                    ~
                                // noinspection ES6RedundantAwait, this helps synchronize the await and expect mixture.
                                return cinemaPlan.get(0);

        node:internal/process/task_queues:96:5
        jasmine-spec-reporter: unable to open 'node:internal/process/task_queues'
        Error: ENOENT: no such file or directory, open 'node:internal/process/task_queues'

        P:/projects/workspace/net.twisterrob.cinema/Heroku/test/src/plans.spec.js:24:17

                        it('should be removable', async function () {
                                const plan = await gotoPlan();
                        ~
                                expect(plan.root).toBeDisplayed();
                                expect(plan.delete).toBeDisplayed();